### ISSUE TITLE
Restructure app template (code and files) to adhere to default .Net Analyzer rules

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-template-dotnet#110]
Goal: Have the same set of rules applied to the development of apps and the app template as we have everywhere else. Avoid warnings and ignore statements in code when we pull app code into integration tests. We should have a warning free template to lead by example.

**Comment by ivarne** [comment]
Some of the rules you apply are rather strict (maybe say unpleasant). I have no issue with them on library code, but for app developers I think we should have fewer requirements.

Especially the requirement to have xml doc for methods and blank lines after closing }, and before singe line comments is something that I don’t think should be required in apps.
