### ISSUE TITLE
Drop the need for overriding AppBase.cs

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-template-dotnet#111]
Goal: Base overrides on Dependency Injection with well defined interfaces instead.

**Comment by tjololo** [comment]
I have started the work on this issue in branch https://github.com/Altinn/app-template-dotnet/tree/chore/90-111-drop-appbase-overrides. The integrationtests run after an massive rewrite of all the apps used in most of the test.
The branch assumes that the machine running the tests has the 7.0.0-local1 version of Altinn.App.* libraries.
