### ISSUE TITLE
Move from AppBase and overriding methods as extension points and over to dependency injection and dotnet event pattern

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-template-dotnet#114]
Goal: Reduce breaking changes when implementation changes as the base class approach is sensitive when it comes to introducing breaking changes.

**Comment by tjololo** [comment]
In branch https://github.com/Altinn/app-lib-dotnet/tree/chore/90-114-event-pattern I have a suggestion for an event pattern.
