### ISSUE TITLE
Move PDF generation out of AppBase

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-template-dotnet#116]
Goal: Allow for easy replacement of PDF generation, both for Altinn to create a new version and for app developers to create their own.

**Comment by tjololo** [comment]
I may have moved the logic out of AppBase in my event pattern branch. The code is just copied around to another place so this issue is still relevant only the file we are moving from has changed

**Comment by ivarne** [comment]
Should probably close the issue now that AppBase is gone.
