### ISSUE TITLE
New app repository contains JWTValidationCert.cer file

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/app-template-dotnet#158]
## Description

The file [JWTValidationCert.cer](https://github.com/Altinn/altinn-studio/blob/master/src/studio/AppTemplates/AspNet/App/JWTValidationCert.cer) 
is included in the App folder for a new application. Cannot see how this is a required file in the app template. 

## Expected behavior
This file should not be a part of the app template.

**Comment by RonnyB71** [comment]
@tjololo you deleted this file - right? Can we close this issue?

**Comment by ivarne** [comment]
It appeared in a test app from a week ago https://altinn.studio/repos/xivne/test1/src/branch/master/App/JWTValidationCert.cer

**Comment by nkylstad** [comment]
Yep, looks like it's still in the Studio copy of the template. Once we can start using the new solution of fetching app template directly from app-template-dotnet this will be solved. We have a PR for that ready which is blocked, pending a new release of `app-template-dotnet` @RonnyB71 @tjololo

**Comment by tjololo** [comment]
Not removed in the altin-studio copy, but we plan to release a new version of app-template later today/early tomorrow. Then the PR in studio is unblocked and we can close this issue

**Comment by nkylstad** [comment]
Fetching app template from app-template repo is merged to master. This will be fixed in studio prod when we deploy.
