### ISSUE TITLE
Remove link to Altinn-DIN font

### ISSUE THREAD

**Issue by bjosttveit** [Altinn/app-template-dotnet#181]
### Description

In the next release of app-frontend, the font is switched to use `Inter`, and this font is added directly through app-frontend's css bundle, so a link in app-template is not needed https://github.com/Altinn/app-frontend-react/pull/1173. Therefore, the link to Altinn-DIN should be removed since this will no longer be used.

**Comment by RonnyB71** [comment]
Blocked by the release of 3.66
