### ISSUE TITLE
Update application to support that user can go back from confirmation page

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-template-dotnet#21]
## Description
It should be possible to go back from the confirmation task to the previous task or whatever defined task in the BPMN process. 

In the below example SequenceFlow_4 takes the process from Task_2 (confirmation) to Task_1 (data)

```xml
  <bpmn2:process id="Altinn_Data_Confirmation_Process" isExecutable="false">
    <bpmn2:startEvent id="StartEvent_1">
      <bpmn2:outgoing>SequenceFlow_1</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:task id="Task_1" name="Fyll ut skjema" altinn:tasktype="data">
      <bpmn2:incoming>SequenceFlow_1</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_2</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:task id="Task_2" name="Bekreft skjemadata" altinn:tasktype="confirmation">
      <bpmn2:incoming>SequenceFlow_2</bpmn2:incoming>
      <bpmn2:outgoing>SequenceFlow_3</bpmn2:outgoing>
    </bpmn2:task>
    <bpmn2:endEvent id="EndEvent_1">
      <bpmn2:incoming>SequenceFlow_3</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="SequenceFlow_1" sourceRef="StartEvent_1" targetRef="Task_1" />
    <bpmn2:sequenceFlow id="SequenceFlow_2" sourceRef="Task_1" targetRef="Task_2" />
  <bpmn2:sequenceFlow id="SequenceFlow_4" sourceRef="Task_2" targetRef="Task_1" />
    <bpmn2:sequenceFlow id="SequenceFlow_3" sourceRef="Task_2" targetRef="EndEvent_1" />
  </bpmn2:process>
```

## Screenshots
TODO: create a conformation view with navigation buttons

## Considerations
- The BPMN process will need to define what kind of sequence flows that is possible out from the confirmation step
- We would need to know what is forward and what is backward. (depending on how the button layout would be)
- We need language support so the naming of a button can be defined
- We need to define what type of authorization action that is required to navigate backward. 

## Acceptance criteria
- It is possible to navigate from confirmation task and backward to a given task in the process
- BPMN process is the source for the possible flows

## Development tasks
- [ ] Design process navigation on the confirmation page. (this might be reused for other task types in the future)
- [x] Analyse and design how we can define on the sequence flow that a flow is backward/forward (or some other concept (alternative flow?))
- [ ] Update API/models so App Frontend can know about the navigation possibilities
- [ ] Updatate App frontend to add navigation on confirmation view
- [x] Update App backend to enable logic on process backward/navigation to a specific task

**Comment by FinnurO** [comment]
Duplicate
