### ISSUE TITLE
Support fileupload in confirmation view

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-template-dotnet#24]
## Description

In some scenarios, there is a need for uploading file attachments at the confirmation task. 

## Screenshots

![image](https://user-images.githubusercontent.com/13309071/140070401-339978e8-703a-48f1-8a0f-2d050a151b26.png)

## Considerations

In some scenarios, we need to validate that a specific attachment is uploaded and in some scenarios, it is different attachment types that needs to be uploaded. Do we then need support for multiple attachments?

How to configure the file upload

The current datatype configuration is assumed to be sufficient. 

## Acceptance criteria
- Possible to upload files
- Possible to define which file is being uploaded 
- Possible to have task validation on the files uploaded. (out of the box or more complex based on data)

## Specification tasks

- [ ] Development tasks are defined

## Development tasks
- [ ] Add configuration for file upload
- [ ] Add file upload support in confirmation view. USe standard API for uploads

**Comment by FinnurO** [comment]
@nkylstad and @lorang92 Is this issue solved by the completion of #482?

**Comment by lorang92** [comment]
@FinnurO yeah, confirmed that this is working after we completed #482. Note that in order to support this the app developer must configure a custom confirm page as described in [docs.](https://docs.altinn.studio/app/development/configuration/process/customize/#custom-form-layout).

**Comment by FinnurO** [comment]
Closing. Solved by https://github.com/Altinn/app-frontend-react/issues/482
