### ISSUE TITLE
Liveness and readiness probe of pods in Altinn Apps

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/app-template-dotnet#50]
## Description
To increase robustness we should implement /health/ready and /health/alive endpoints in all our applications as described [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1).

At first both should just be the same simple liveness-check that Kubernetes should use (see example). Over time we can add more complex readyness checks if the need arises.

## Acceptance criteria
- Probes are implemented for Apps

## Development tasks
- [x] Implement endpoint in app nugetpackage 
- [x] Update helm chart for apps
- [x] QA
- [x] Documentation is updated 
- [x] Manual test is complete (if relevant)
- [x] Update app template in studio

**Comment by jeevananthank** [comment]
after the health check is enabled in the app, application insights for the app reports the requests for the health check.
