### ISSUE TITLE
`RunProcessDataWrite` should state what field was changed, the old value, and the new value

### ISSUE THREAD

**Issue by simendsjo** [Altinn/app-template-dotnet#55]
Some calculations has to be done only once, or only when specific data changes. `RunProcessDataWrite` doesn't include the field or old value, making this impossible without introducing extra helper fields in the data model, which again leaks to later steps in our process.

My use-case is something like the following in pseudokode. Note that "orgnr" and "orgname" in my example is only visible if certain other conditions are true.

```
RunProcessDataWrite(Instance instance, Guid? dataId, object data, string field, object oldValue, object newValue) {
    if (field = "orgnr" && oldValue != newValue) {
        var party = _registerService.ER.GetOrganization(newValue)
        data.orgname = party.Name
        return updated
    }
    return not-updated
}
```

**Comment by simendsjo** [comment]
[Discussion in slack](https://altinn.slack.com/archives/C02EJ9HKQA3/p1646640872795879)

**Comment by StianVestli** [comment]
org/ssb

**Comment by ivarne** [comment]
This has been fixed by reporting the previous data model from v8
