### ISSUE TITLE
Upload attachments in a multipart request fails with 500

### ISSUE THREAD

**Issue by jeevananthank** [Altinn/app-template-dotnet#65]
## Description
Upload attachments in a multipart request fails with 500 and a stack trace.

## To Reproduce
1. Send a POST call to create an instance with multipart data with form data and attachment
2. The response is 500 with stack trace
> System.NullReferenceException: Object reference not set to an instance of an object.
   at Altinn.App.Common.RequestHandling.RequestPartValidator.ValidatePart(RequestPart part)
   at Altinn.App.Common.RequestHandling.RequestPartValidator.ValidateParts(List`1 parts)
   at Altinn.App.Api.Controllers.InstancesController.Post(String org, String app, Nullable`1 instanceOwnerPartyId)
   at lambda_method205(Closure , Object )

## Expected behavior
Instance should be created with form data and attachment as data elements

## Additional info
env: localtest
app: ttd/apps-test
ref postman [collection](https://github.com/Altinn/altinn-studio/blob/master/src/test/Postman/collections/Local-Test.postman_collection.json)
request: Post multipart with attachment

**Comment by Magnusrm** [comment]
Discussed the possible solutions during the daily meeting 18.05 and there seemed to be agreement that the first proposed solution should be implemented

**Comment by olemartinorg** [comment]
Tested OK! :1st_place_medal: 

Postman tests were not straight forward to get up and running, but once I figured out how they were supposed to be executed, I could verify the change solved the issue.
