### ISSUE TITLE
Bug: Cannot send documents with ÆØÅ in title through eFormidling

### ISSUE THREAD

**Issue by allinox** [Altinn/app-template-dotnet#89]
## Description

When attempting to send the PDF containing the inputted data from an app (skjenkebevilling) through eFormidling, the app crashes on sending and we receive the error: "File(s) defined in arkivmelding, but not found in message: Søknad om skjenkebevilling.pdf"

Through debugging with Stephanie, we've realized that this seems to happen whenever the filename that is to be sent through contains one or more of the Norwegian letters (æøå).

## To Reproduce

1. Go to an app that has eFormidling integration
2. Attempt to send a document with a name containing Norwegian characters
3. The app fails

## Expected behavior

The most ideal would of course be to allow files containing Norwegian characters to be sent through eFormidling.
In our case, the name of our form contains the letter "ø" and even if that wasn't the case, we wish for the user to upload attachments that we then need to pass through eFormidling as well. These attachments could easily contain Norwegian characters. (Possibly even other characters when I think about it... Perhaps that's something that needs to be considered too?)

## Additional info
Known issue for the people working with efm. See their suggestion below. 
![image](https://user-images.githubusercontent.com/47737608/169504378-c896d0d6-aedd-4aad-9f38-00d7b3e87145.png)

**Comment by acn-sbuad** [comment]
nuget v 6.0.1, can be tested with app ttd/eformidling-app

**Comment by tba76** [comment]
Testet ok!
